#!/bin/bash 

function die {
  msg = shift
  echo msg
  exit -1
}

# Source code root directory 
export ROOT=$(pwd)

# Build tree root 
export BUILD_ROOT=$ROOT/build 

# Dependencies build root 
export DEPS_TARGET_ROOT=$BUILD_ROOT/deps/

# External Erlang applications directory
export ERL_DEPS_TARGET_ROOT=$DEPS_TARGET_ROOT/erl/
export ERL_DEPS_TARGET_BIN=$ERL_DEPS_TARGET_ROOT/bin 
export ERL_LIBS=$ERL_DEPS_TARGET_ROOT

ERL=$(which erl)
[ $? == 0 ] || die "Could not find erl in \$PATH"
echo Using Erlang from $(dirname $(dirname $ERL))

export PATH=$ERL_DEPS_TARGET_BIN:$PATH

